{% set name = "GHEtool" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/GHEtool-{{ version }}.tar.gz
  sha256: f8496c0619d9cf465e714239df2be0f43ee0f269e8c01d1f601bcafbf179ed37

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=54
    - wheel
    - pip
  run:
    - python >=3.7
    - matplotlib-base >=3.5.2
    - numpy >=1.23.1
    - pandas >=1.4.3
    - pygfunction==2.3.0
    - pyside6 >=6.4.1
    - configparser >=5.3.0
    - scipy >=1.8.1
    - pytest >=7.1.2
    - scikit-optimize >=0.9.0

test:
  imports:
    - GHEtool
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wouterpeere/GHEtool
  summary: Python package for borefield sizing
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - wouterpeere
